#!/bin/bash

PROJECT_HOME=$(cd $(dirname "$0")/.. && pwd)
CLOJUREC_HOME="$PROJECT_HOME/.lein-git-deps/clojurec"
TMP_DIR="$PROJECT_HOME/target/_clojurec"

TARGET_FILE="$PROJECT_HOME/$1"
MAIN=$2
TMP_FILE="$TMP_DIR/driver.c"

rm -f $TARGET_FILE
cd $CLOJUREC_HOME
lein run -d $MAIN $TMP_DIR
mkdir -p $(dirname $TARGET_FILE)
mv $TMP_FILE $TARGET_FILE
